### ISSUE TITLE
"Other" word in specific sequence hung up program

### ISSUE THREAD

**Issue by noriiOla** [mmichelsonIF/hearst_patterns_python#9] opened 2019-05-26 08:06 UTC
Hi,
I did put the sequence below in program.
hyps1 = h.find_hyponyms('The German composers Christoph Gluck (18th century) and Richard Strauss (20th century), the German-French composer Jacques Offenbach (19th century), the Russian composer Igor Stravinsky (20th century), and many others have set Greek mythological themes to music').
Program stopped working, not because of crash. It just hung up.
If I delete "other" word then it works great.
I wonder, why it happens?

**Comment by MollieBakal** [comment] 2019-06-25 18:58
I know why this happens, if that helps.
The noun chunk tripping up the program is "many others". The problem is that both "many" and "other" are in the adjective stopword list, and "others" lemmatizes to "other". Both words are caught by line 77, so nothing is appended to chunk_arr in 79. Chunk_lemma, the string, becomes "", replacement_value is "NP_", and .replace() inserts that between every other character.
Line 101, matches.re, hangs on what seems like an infinite loop when it searches for the third regex; '((NP_\\w+ ?(, )?)+(and |or )?other NP_\\w+)'.
I don't know what makes that one different from the others, which just produce no matches.

**Comment by MollieBakal** [comment] 2019-06-25 19:51
It's probably just analyzing all 300 NP_ in pairs (recursively? This might be factorial or exponential time) to try to determine if any contain an "other " within them. Not sure why the two regex before execute quickly but this doesn't. It also passes the other two regex in the basic one, but hangs on the first of the extended patterns. I'm wondering if this has something to do with the fact that the other patterns have an ending which isn't "\w+".

**Comment by MollieBakal** [comment] 2019-06-26 15:05
Opened pull request #10 to fix.

**Comment by mmichelsonIF** [comment] 2019-06-26 21:15
Thank you for the contribution! I merged.

**Closed as completed** 2019-06-26 21:16 UTC
